tags$html(
  tags$head(
    tags$title('About page')
  ),
  tags$body(
    h3("Project Team"),
    p(strong("Principle Investigator:")),
    p(a( href='http://www.oeb.harvard.edu/faculty/richardson/',target='_blank','Andrew D. Richardson, Harvard University' )),
    br(),
    p(strong("Co PI's")),
    p(a( href='http://www.bu.edu/earth/people/faculty/mark-friedl/', target='_blank','Mark Friedl, Boston University')),
    p(a( href='http://www.eos.unh.edu/Faculty/Frolking', target='_blank','Steve Frolking, University of New Hampshire')),
    br(),
    p(strong('Data manager')),
    p(a( href='mailto:thomas.milliman@unh.edu?subject=PhenoCam%20Data', target='_blank', 'Tom Milliman, University of New Hampshire')),
    br(), 
    p(strong("Students and postdocs")),
    p(a( href='http://www.khufkens.com/', target='_blank','Koen Hufkens, postdoc, Harvard University')),
    p(a( href='http://margaretkosmala.com/', target='_blank','Margaret Kosmala, postdoc, Harvard University')),
    p("Min Chen, postdoc, Harvard University"),
    p("Don Aubrecht, postdoc, Harvard University"),
    p("Eli Melaas, postdoc, Boston University"),
    p("Josh Gray, postdoc, Boston University"),
    p("Steve Klosterman, PhD student, Harvard University"),
    br(), 
    p(strong('Collaborators')),
    p('Sandra Henderson, NEON'),
    p('Jake Weltzin, USA-NPN'),
    br(), 
    p(strong('Past Contributors')),
    p("Michael Toomey, former postdoc, Harvard University"),
    p("Trevor Keenan, former postdoc, Harvard University"),
    p("Oliver Sonnentag, former postdoc, Harvard University"),
    p("Bobby Braswell, research faculty, University of New Hampshire (now @ Applied GeoSolutions)"),
    br(),
    h3('Motivation'),
    p("Reducing uncertainties about the role of terrestrial ecosystems in the global carbon [C] cycle requires better understanding of the spatial and temporal variation in biologically-mediated sources and sinks of C. Particularly in temperate and boreal forest ecosystems, phenological events such as spring leaf emergence and autumn senescence exert strong control on primary productivity and are therefore critical to ecosystem C cycling. Phenology also influences hydrologic processes, as leaf-out is accompanied by an increase in evapotranspiration; nutrient cycling processes, as senescence results in fresh litter (nutrient) inputs to the forest floor; and feedbacks to the climate system, as the amount and condition of foliage present affects surface energy balance, albedo, and surface roughness. Phenology also influences ecological interactions among individuals (e.g., competition) and across trophic levels (e.g., herbivory)."),
    p("Phenology has been shown to be a robust integrator of the effects of year-to-year climate variability and longer-term climate change on natural systems (e.g., recent warming trends). Experimental studies have shown how other global change factors (e.g., elevated CO2 and N deposition) can also influence phenology. There is a need to better document biological responses to a changing world, and improved phenological monitoring at scales from individual organisms to ecosystems, regions and continents will contribute to achieving this goal."),
    br(),
    h3("The PhenoCam Network"),
    p('We initiated the PhenoCam Network in order to provide automated, near-surface remote sensing of canopy phenology across the northeastern United States and adjacent Canada. This work was funded by two grants (2007-2009, 2009-2011) from the Northeastern States Research Cooperative. Following pilot work at Bartlett Experimental Forest we installed high-resolution digital cameras (webcams) at more than a dozen established research sites distributed throughout this region. Images from these cameras are uploaded to the PhenoCam server every half hour, and we then use simple analysis techniques to extract quantitative color information from each picture. Canopy greenness indices thus provide information about the amount of foliage present, and its color. In this way, image analysis of archived digital camera images provides an objective means by which canopy phenology can be monitored and quantified, at relatively low cost and with minimal personnel expenses, without the need for a human observer.'),          
    p('At many of the PhenoCam network sites, cooperating researchers are conducting ongoing measurements of surface-atmosphere exchange of carbon and water using the eddy covariance method, and these flux data are being used to evaluate the implications of seasonal changes in canopy state for ecosystem function. We are actively seeking to establish new collaborations with existing AmeriFlux sites.'),
    p('Unlike conventional remote sensing, near-surface remote sensing provides imagery that is continuous in time, free of contamination by clouds, and not requiring correction for atmospheric effects. A key problem with satellite remote sensing (e.g. MODIS imagery) is the coarse spatial resolution; digital camera imagery, on the other hand, offers the opportunity to either integrate the phenological signal across the whole canopy, or to identify individual tree crowns and conduct separate analyses for different species. At the same time, the PhenoCam network provides information needed to link what is actually happening on the ground and what is observed by airborne and satellite sensors. Thus data from this project will contribute to efforts in which remote sensing is used to scale from intensively monitored sites to more extensive spatial domains.'),
    p("Funding from the National Science Foundation’s Macrosystems Biology Program (award EF-1065074) has enabled the expansion of the network, a focus on broader science questions, and improvements to our online data visualization and delivery tools. Our goal is to function as a continental-scale phenological observatory, spanning as wide a range of biogeoclimatic zones and vegetation types as possible (Figure 1). New cameras have been installed at research sites from Alaska to Panama, Hawaii to Georgia, and Arizona to Wisconsin.  More than 80 cameras, deployed following our standardized protocol, are currently uploading half-hourly imagery to the PhenoCam server."),
    img(src="http://phenocam.sr.unh.edu/static/img/biome_image.png", width="100%"),
    p(tags$i("Figure 1. Vegetation canopy greenness, as quantified by the green chromatic coordinate (GCC) using PhenoCam imagery, in relation to seasonal patterns of monthly precipitation (blue bars) and air temperature (red bars).  Green lines correspond to GCC for trees, and brown to GCC for grasses, in camera field of view. The seasonal patterns, and interannual variability, vary among sites in relation to climate drivers and vegetation type.")),
    br(),
    h3("Research Questions"),
    p('The primary objective of the PhenoCam project is to use automated, near-surface remote sensing to provide continuous, real-time monitoring of vegetation phenology across a range of ecosystems and climate zones.'),
    p('The science questions motivating the project are as follows:'),
    tags$ol(tags$li("How do photoperiod, temperature, and precipitation govern phenological transitions in different vegetation types?"),
            tags$li("How will phenology respond to climate change, and what are the associated uncertainties?"),
            tags$li("How will these phenological shifts impact ecosystem processes, and climate system feedbacks, related to carbon and water?")),
    br(),
    h3("Data Sharing"),
    p("We make all of our imagery freely available for download by the community; all that is required is that you register for a user account. Derived data products can be viewed in near-real-time on ROI page for each site. We are finalizing data and metadata formats and hope to make the processed data available to registered users by June, 2014. Please email PI Richardson for more information."),
    p("Our fair use policy reads as follows:"),
    p("Imagery from the PhenoCam archive is made publicly available to promote the study and analysis of phenology in different ecosystem types, and to improve our understanding of how phenology is driven by environmental factors. We encourage you to download imagery for use in your own research and publications. While considerable time and effort has gone into compiling and maintaining this data archive, we have no ownership over many of the images stored here, particularly those that were provided by cooperating federal agencies, e.g. the US National Park Service and USDA Forest Service. We do ask, however, that you send an email to PI Richardson indicating how you intend to use the data, and any publication plans you might have, so that we can minimize overlapping efforts. We would certainly welcome invitations to participate as collaborators on your project. If we are already working on a topic similar to what you have in mind, we may ask that you give us a reasonable chance to finish our manuscript and submit it for publication first. Finally, please recognize the data source as a citation or in your acknowledgments, and cite the relevant papers we have already published on the topic (e.g., Richardson et al. 2007, 2009; Morisette et al. 2009, Jacobs et al. 2009, Sonnentag et al. 2012).")
  )
)
